# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:/Program Files/Java/jdk-25.0.2
# Fabric Properties
minecraft_version=26.2
loader_version=0.19.0
# Mod Properties
mod_version=1.0
maven_group=net.kztmc.mc
archives_base_name=blocktuner-26.2
fabric_version=0.161.0+26.2